//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int IDAttachment { get; set; }
        public System.Guid IDLifeCycle { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual LifeCycle LifeCycle { get; set; }
    }
}
