//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomLookup
    {
        public int IDCustomLookup { get; set; }
        public int IDLookupType { get; set; }
        public string Val1 { get; set; }
        public string Val2 { get; set; }
        public int Sequence { get; set; }
    
        public virtual LookupType LookupType { get; set; }
    }
}
