//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionXTab
    {
        public int IDFunctionXTab { get; set; }
        public int IDFunction { get; set; }
        public int IDTab { get; set; }
    
        public virtual Tab Tab { get; set; }
    }
}
