//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Function()
        {
            this.LevelXFunctions = new HashSet<LevelXFunction>();
        }
    
        public int IDFunction { get; set; }
        public string Name { get; set; }
        public Nullable<int> Direction { get; set; }
        public string PastTenseFunction { get; set; }
        public Nullable<int> IDTab { get; set; }
        public bool IsAlignedLeft { get; set; }
        public int FunctionOrder { get; set; }
    
        public virtual Tab Tab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelXFunction> LevelXFunctions { get; set; }
    }
}
