//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIG()
        {
            this.LifeCycles = new HashSet<LifeCycle>();
            this.UDFInstances = new HashSet<UDFInstance>();
        }
    
        public System.Guid IDGig { get; set; }
        public int IDUPW { get; set; }
        public Nullable<int> IDContractor { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public string ContractorGIGNumber { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual UserXProjectXWorkFlowUserGroup UserXProjectXWorkFlowUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeCycle> LifeCycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDFInstance> UDFInstances { get; set; }
    }
}
