//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LifeCycle()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public System.Guid IDLifeCycle { get; set; }
        public System.Guid IDGig { get; set; }
        public Nullable<int> IDLevelXFunction { get; set; }
        public int LoggedByID { get; set; }
        public Nullable<int> OwnedByID { get; set; }
        public Nullable<int> AssignedToID { get; set; }
        public System.DateTime LoggedOn { get; set; }
        public string Detail { get; set; }
        public bool ISSubmitted { get; set; }
        public int IDLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual GIG GIG { get; set; }
        public virtual Level Level { get; set; }
        public virtual LevelXFunction LevelXFunction { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
