//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQFINFO.Repository.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDFValidation
    {
        public int IDUDFValidation { get; set; }
        public int IDUDFDefinition { get; set; }
        public int IDUDFValidationDefinition { get; set; }
        public string Message { get; set; }
    
        public virtual UDFDefinition UDFDefinition { get; set; }
        public virtual UDFValidationDefinition UDFValidationDefinition { get; set; }
    }
}
